stages:
  - build

build-user-service:
  stage: build
  tags:
    - docker
  image: maven:3.9.9-eclipse-temurin-17

  script:
    - java -version
    - mvn -version
    - cd user-service
    - mvn clean package