stages:
  - build

build-user-service:
  stage: build
  tags:
    - docker
  script:
    - docker run --rm
      -v "$CI_PROJECT_DIR/user-service:/app"
      -w /app
      maven:3.9.9-eclipse-temurin-17
      mvn clean package