stages:
  - test

runner-test:
  stage: test
  tags:
    - docker
  image: alpine:latest
  script:
    - echo "================================="
    - echo "GitLab Runner is working!"
    - echo "Docker executor is working!"
    - echo "================================="
    - cat /etc/os-release