spring.datasource.url=jdbc:postgresql://commerce-postgres:5432/commerce_product_db
spring.datasource.username=commerce_user
spring.datasource.password=commerce_password

management.endpoint.health.show-details=always

logging.level.com.nisum.productservice=INFO