spring.application.name=product-service
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/commerce_product_db}
spring.datasource.username=${DB_USERNAME:commerce_user}
spring.datasource.password=${DB_PASSWORD:commerce_password}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG
logging.level.com.nisum.productservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level [%thread] %logger{36} - %msg%n
#logging.structured.format.console=logstash

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=product-service
info.app.description=E-commerce Product Service
info.app.version=1.0.0

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
product.cache.ttl=30m
product.cache.negative-ttl=2m

################################################
######### KAFKA CONFIGURATION ##################
################################################
spring.kafka.bootstrap-server= localhost:9092
kafka.test.rollback=true
