apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
  - ../../base

configMapGenerator:
  - name: user-service-config
    literals:
      - DB_URL=jdbc:postgresql://postgres:5432/commerce_db